# Generated by Django 4.2.1 on 2023-06-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakultet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='sub_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Fakultet_name'),
        ),
    ]
