# Generated by Django 4.2.1 on 2023-06-21 10:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Markaz nomi')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='Markaz nomi')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Markaz nomi')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Markaz nomi')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Content')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Content')),
                ('sees', models.IntegerField(default=1, verbose_name='Kurilganlar')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update time')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('name_uz', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=250, null=True, verbose_name='Name')),
                ('image', models.ImageField(upload_to='./partner/', verbose_name='Image')),
                ('url', models.URLField(verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Rectory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('image', models.ImageField(upload_to='./rectory/', verbose_name='Image')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Information')),
                ('content_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Information')),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Information')),
                ('content_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Information')),
                ('academic_title', models.CharField(max_length=200, verbose_name='Academic Title')),
                ('academic_title_uz', models.CharField(max_length=200, null=True, verbose_name='Academic Title')),
                ('academic_title_en', models.CharField(max_length=200, null=True, verbose_name='Academic Title')),
                ('academic_title_ru', models.CharField(max_length=200, null=True, verbose_name='Academic Title')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_uz', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_en', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('address_ru', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('fax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fax Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('is_rector', models.BooleanField(default=False)),
                ('position', models.CharField(max_length=250, verbose_name='Position')),
                ('position_uz', models.CharField(max_length=250, null=True, verbose_name='Position')),
                ('position_en', models.CharField(max_length=250, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(max_length=250, null=True, verbose_name='Position')),
                ('reception_time', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Qabul vaqti')),
                ('reception_time_uz', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Qabul vaqti')),
                ('reception_time_en', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Qabul vaqti')),
                ('reception_time_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Qabul vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='F.I.O')),
                ('image', models.ImageField(blank=True, default='./employee/avatar.png', null=True, upload_to='./employee')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefon')),
                ('academic_title', models.TextField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('position_uz', models.CharField(blank=True, max_length=200, null=True)),
                ('position_en', models.CharField(blank=True, max_length=200, null=True)),
                ('position_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('is_chief', models.BooleanField(default=False)),
                ('reception_time', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('reception_time_uz', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('reception_time_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('reception_time_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department')),
            ],
        ),
    ]
