# Generated by Django 4.2.1 on 2023-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('icon_class', models.CharField(max_length=250, verbose_name='Icon Name')),
                ('url', models.URLField(verbose_name='Url')),
            ],
        ),
    ]
